name: Release New Archive File

on:
  push:
    paths:
      - 'Archive/**'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest file in Archive folder
        id: latest_file
        run: |
          FILE=$(find Archive -type f | sort -r | head -n 1)
          echo "file_path=$FILE" >> $GITHUB_OUTPUT
          echo "file_name=$(basename "$FILE")" >> $GITHUB_OUTPUT

      - name: Calculate SHA-256
        id: sha256
        run: |
          HASH=$(sha256sum "${{ steps.latest_file.outputs.file_path }}" | awk '{print $1}')
          echo "sha256=$HASH" >> $GITHUB_OUTPUT

      - name: Extract version from pchatt.mcreator
        id: version
        run: |
          VERSION=$(jq -r '.workspaceSettings.version' Source/pchatt.mcreator)
          echo "version_tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "release_name=ParanoidChatter $VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          name: ${{ steps.version.outputs.release_name }}
          body: |
            [![discord server](https://cdn.modrinth.com/data/cached_images/6d9796c521a3261b9a7e4c3eb6b1c3d2dfe4c112.png)](https://optb.short.gy/dsc) [![Github](https://cdn.modrinth.com/data/cached_images/ae65154a7b076cd508f14975a27d1e75e3449a1d.png)](https://github.com/OptionallyBlueStudios/MC-ParanoidChatter) [![Modrinth Link-Banner](https://cdn.modrinth.com/data/cached_images/b9c43eaea7fc523285ae0981829b84e206672b48.png)](https://modrinth.com/mod/optb-pchatt)

            # its here. its watching. its chatting.

            This is a paranoia mod for Minecraft based around the chat!
            <details>
            <summary>Developer Commands</summary>

            - /pchatd-ranmes - Check The Random Message Function

            </details>

            <details>
            <summary>Features</summary>

            - Random Messages (after 25 minutes of game time, 1 in 700 chance per tick)

            </details>

            <details>
            <summary>Features to come</summary>

            - idk I just made this mod.. gotta think about it more.

            </details>

            <details>
            <summary>This mod works well with..</summary>

            - [The Broken Script](https://modrinth.com/mod/the-broken-script) (TBS)
            - [no_moon.jar](https://modrinth.com/mod/no_moon.jar) (NM.J)
            - [Paranoia](https://modrinth.com/mod/paranoia) (PN)
            You can use multiple of these at the same time. For NM.J and TBS, make sure to enable TBS mode in NM.J config.

            </details>

            <br>
            <br>

            <details>
            <summary>Credits</summary>

            - [This is not the same as Horror Messages](https://modrinth.com/mod/horror-messages)

            - [Badges at the top are from](https://github.com/LopyMine/Particle-Effects/blob/master/README.md?plain=1)

            - Release workflow (on GitHub) generated by AI

            </details>

            The file SHA-256 Hash Is: `${{ steps.sha256.outputs.sha256 }}`
          files: ${{ steps.latest_file.outputs.file_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
